# Generated by Django 4.2.30 on 2026-07-05 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkedin_app', '0008_post_video_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_link',
            field=models.CharField(blank=True, help_text='Any URL or contact link (Telegram, WhatsApp, website…)', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, help_text='image, video, or file', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='allowed_viewers',
            field=models.ManyToManyField(blank=True, related_name='allowed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
    ]
